- pom.xml
Post Jenkins fork as per instruction on the hosting issue updated the Wiki link in pom and also added <scm> tag details.
> Updated pom with Wiki link and scm tag

- src/main/resources/com/mathworks/ci/MatlabBuilder/runMatlabTests.m
added support for creating test suites for MATLAB versions less than R2016a
> testsuite support for MATLAB version less than R2016a

- src/main/java/com/mathworks/ci/MatlabBuilder.java
- src/main/java/com/mathworks/ci/MatrixPatternResolver.java
- src/main/resources/com/mathworks/ci/MatlabBuilder/config.jelly
- src/test/java/com/mathworks/ci/MatlabBuilderTest.java
- src/test/java/com/mathworks/ci/MatlabBuilderTester.java
Added Jenkins Environment variable support for both MATLAB root field and Custom command field. 
Added unit tests for the same.
> Added support for Jenkins environment variables.

- src/main/java/com/mathworks/ci/MatlabBuilder.java
- src/main/java/com/mathworks/ci/MatlabBuilderConstants.java
- src/main/resources/com/mathworks/ci/MatlabBuilder/RunTestsAutomaticallyOption/help-taModelCoverageChkBx.html
- src/main/resources/com/mathworks/ci/MatlabBuilder/runMatlabTests.m
- src/main/resources/config.properties
- src/test/java/com/mathworks/ci/MatlabBuilderTest.java
- src/test/resources/testconfig.properties
- src/test/resources/versioninfo/R2018a/VersionInfo.xml
Two fixes here:
1) There was an incorrect syntax in runMatlabTests call for versions below R2018b - [g2136203](http://komodo.mathworks.com/main/gecko/view?Record=2136203)
2) Cobertura model coverage is not supported in R2018a. It is only supported from R2018b onwards.
> Fix for g2136203 and cobertura model coverage

- src/main/java/com/mathworks/ci/MatlabBuilder.java
eval uses single quotes instead double quotes
> Fixed eval string issue.

- README.md
- src/main/java/com/mathworks/ci/MatlabBuilder.java
- src/main/java/com/mathworks/ci/MatlabBuilderConstants.java
- src/main/resources/com/mathworks/ci/MatlabBuilder/RunTestsAutomaticallyOption/config.jelly
- src/test/java/com/mathworks/ci/MatlabBuilderTest.java
- "PDF test report" option throws errors when running on MAC platform. Refer https://github.com/mathworks/jenkins-matlab-plugin/issues/48 for details on the issue.
- Because of the issue, I am removing the PDF test report option from UI so that we don't hold the release. We can add the PDF option once the issue is resolved.
Note: I didn't remove the business logic for PDF test report feature from runMatlabTests.m script.
The UI now looks like this:
> Removed PDF test report option from plugin UI

- src/main/resources/com/mathworks/ci/MatlabBuilder/runMatlabTests.m
Note: Need access to matlab in CI of this project to test this file in automation. This will instead be addressed by scriptgen infrastructure.
> Fix empty plugin bug

- pom.xml
- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/main/java/com/mathworks/ci/RunMatlabCommandBuilder.java
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/main/java/com/mathworks/ci/UseMatlabVersionBuildWrapper.java
- src/test/java/com/mathworks/ci/RunMatlabCommandBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
Matrix builds were failing due to synchronization issue . since mtalb_runner script was used by both builds with same name and same location .  the namespacing issue caused accidental deletion of the runner script by by different thread than it had create. Resolved this issue by letting each build step to copy its own file in tmp folder and delete the same file. File uniqueness is mainatined by adding a timeStamp to the file name.
> Fix for matrix issue 

- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/main/java/com/mathworks/ci/MatlabBuilderConstants.java
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/main/resources/config.properties
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
Fixed the Findbug issue . suppressed the warning as workspace is always passed  through perform() method of builder which will always have workspace available. 
Also there is fix for  matlab scratch file copy issue due to new changes in copyMethod () 
test to check the if scratch file is copied in workspace was missing from new RunMatlabTestsBuilder class which is added now.
> fixed findbug issue and Scratch file copy issue.

- azure-pipelines.yml
Fix our failing Mac builds by using a latest supported Mac image
> Use latest Mac image

- src/main/java/com/mathworks/ci/MatlabBuilderConstants.java
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/runMatlabTests.m
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTester.java
- src/test/java/com/mathworks/ci/UseMatlabVersionBuildWrapperTest.java
Hi Andy , tried your suggestion and figured out the following things.
* Need to maintain the duplicate strings in builder class else it would not resurrect on screen .
* we cant use Interface and / or Abstract class to implement null object pattern  as stapler  class always try to instantiate the class that it has been made a type of 
eg : Artifcat tapArtifact = new NullArtifact();
Stapler will always try to instantiate  Artifcat and it fails when its either abstract or interface with error like below.
Caused by: org.kohsuke.stapler.NoStaplerConstructorException: There's no @DataBoundConstructor on any constructor of interface com.mathworks.ci.RunMatlabTestsBuilder$Artifact
at org.kohsuke.stapler.ClassDescriptor.loadConstructorParamNames(ClassDescriptor.java:247)
at …
> Artifact input change nop

- src/main/java/com/mathworks/ci/MatlabBuilderConstants.java
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/runMatlabTests.m
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTester.java
- src/test/java/com/mathworks/ci/UseMatlabVersionBuildWrapperTest.java
* This change is to support an extra text box which will appear on click of the check boxes for each test artifacts. which will allow users to store the test artifacts at the custom location as shown below.
* Every text box will have default location pre-populated by default.
* Now Parameters to runMatlabTest() file will be specific to the artifact which is selected. unlike list of all the parameters for non selected values. 
* Removed all UI validation against all test artifact check boxes as matlab root is not mandatory for the build.
* Added new unit tests and reduced some invalid test cases.
> Artifact input change

- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/main/java/com/mathworks/ci/RunMatlabCommandBuilder.java
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/main/resources/com/mathworks/ci/RunMatlabCommandBuilder/help-matlabCommand.html
- src/test/java/com/mathworks/ci/RunMatlabCommandBuilderTest.java
* Added support to run MATLAB command through script file to address the issues of "" and other special characters.
* Writing the command in command_UUID.m script file and passing that as a parameter to run_matalb_command(bat|sh) script .
* cleaning the entire temp folder after job completion.
* Few tests which were based on console output of the command has been disabled as now commands cannot be seen on the console window as it will be wrapped in temp script file . I shall add them back to integ-tests once integ-test folders merged.
> Matlab cmd as script

- src/main/java/com/mathworks/ci/MatlabCommandStepExecution.java
- src/main/java/com/mathworks/ci/RunMatlabCommandBuilder.java
- src/test/java/com/mathworks/ci/RunMatlabCommandBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabCommandStepTest.java
* MATLAB is invoked from the workspace instead of invoking it from tmp folder.
* MATLAB command script will be invoked from tmp folder using 'cd' command. ie from workspace first 'cd' to tmp folder and invoke the custom .m script.
* Added tests to verify this behavior
> Run MATLAB command using cd and invoke MATLAB from workspace.

- src/main/java/com/mathworks/ci/MatlabCommandStepExecution.java
- src/main/java/com/mathworks/ci/MatlabRunTestsStepExecution.java
* Fixing Timeout issue for Both Pipeline steps.
* Using `SynchronousNonBlockingStepExecution`  class which does not interrupt the process after 5 minutes.
> Fixed timeout issue for Pipeline steps 

- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/test/java/com/mathworks/ci/RunMatlabCommandBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
- src/test/java/com/mathworks/ci/TestStepExecution.java
Remove extra back slash from temp folder path generation for Windows platform.
Added comment to tests stating Test assumes there's no Matlab installed and no Matlab on Path.
> Fix Java Temp Path discrepancy for Window

- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
This PR is for Hot Fixes Branch and contains fix for issue #132 . These changes have been pre-approved in #135 .
Solution:
Check if in readResolve() test artifact objects have already been deserialized, if yes skip setting to default NullArtifacts.
After Qualification this can be merged and release from Master.
> Fix to retain persisted values for test artifacts 

- CONFIGDOC.md
* With gen script changes in. we need to remove occurrences of `runMatlabTests.m` file from the document.  
* The Script file will not be available to refer once the build is complete. Instead printed on the console log during the build.
> Replaced runMatlabTests.m rferance in document.

- src/main/java/com/mathworks/ci/RunMatlabTestsStep.java
- src/main/resources/com/mathworks/ci/RunMatlabTestsStep/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabTestsStep/help-selectByFolder.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsStep/help-selectByTag.html
- src/test/java/com/mathworks/ci/RunMatlabTestsStepTest.java
* Pipeline support for filtering tests by Folder & Tag name 
* Added two new parameters `selectByFolder` and `selectByTag` are added 
* `selectbyFolder` accepts list of test folder names. eg `selectByFolder: ['testfolder1','testfolder2']`
* Added Integration tests for the same.
> Filter tests

- src/main/java/com/mathworks/ci/MatlabCommandStepExecution.java
- src/main/java/com/mathworks/ci/MatlabRunTestsStepExecution.java
- src/main/java/com/mathworks/ci/RunMatlabCommandBuilder.java
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/main/java/com/mathworks/ci/UseMatlabVersionBuildWrapper.java
After this change both Run test and Run command tasks for freestyle and pipeline will support parallel run on the same host.
Matrix builds will now run job asynchronously unlike earlier behavior where builds were synchronized.
> Asynch build tasks

- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/main/java/com/mathworks/ci/MatlabBuilderConstants.java
- src/main/resources/config.properties
- src/test/java/com/mathworks/ci/RunMatlabCommandBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabCommandStepTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsStepTest.java
- src/test/java/com/mathworks/ci/TestStepExecution.java
In order to support running our MATLAB tasks in docker instance following changes are incorporated in this PR 
* Copying all task related build resources from temp folder to Workspace 
*  There will be temporary folder created named `.matlab` in Jenkins workspace. 
* All resources will be copied in the same `.matlab` folder and will be invoked from the same location .
* Each task will create random folder and assign random names to the files and folders within `.matlab` 
* At the end of the build randomly generated folders and resources will be deleted except `.matlab` folder itself.
* Using 8 bit random UUI instead earlier 32 bit long UUID to cut short the screen space and better readability.
> Support docker

- src/main/java/com/mathworks/ci/UseMatlabVersionBuildWrapper.java
- src/main/java/com/mathworks/ci/Utilities.java
This fixes the unmatched slashes in the MATLAB root path
> Fix for MATLAB root path displayed in Jenkins build logs.

- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/main/java/com/mathworks/ci/MatlabBuilderConstants.java
This PR closes #205 
Details:
1. New strategy to unzip MATLAB Scriptgen package to avoid being picked up by MATLAB Code Coverage tool
2. Supports both regular remote agents and container-based agents.
3. Earlier strategy- unzipping scriptgen inside .matlab folder in workspace.
4. New strategy-copy the scriptgen zip folder to system-specific temporary folder and unzip it here.
5. No helper files in the workspace.
> 2.8.1 snapshot qualification

- src/main/java/com/mathworks/ci/RunMatlabBuildStep.java
- src/test/java/com/mathworks/ci/RunMatlabBuildStepTest.java
- src/test/java/com/mathworks/ci/RunMatlabBuildStepTester.java
This change makes tasks optional in the `runMATLABBuild` step. It will no longer accept tasks as a positional argument. I tried overloading the constructor to see if I could accept an optional positional argument, while also taking the named `tasks` option, but this doesn't seem compatible with Jenkins.
The following will no longer error:
```
node {
runMATLABBuild()
}
```
The following is now the only way to specify tasks:
```
node {
runMATLABBuild(tasks: 'compile test')
}
```
This no longer works:
```
node {
runMATLABBuild 'compile test'
}
```
> update to make tasks options for runMATLABBuild step

- src/main/java/com/mathworks/ci/MatlabBuilder.java
- src/main/java/com/mathworks/ci/MatlabReleaseInfo.java
- src/main/java/com/mathworks/ci/UseMatlabVersionBuildWrapper.java
- src/main/resources/com/mathworks/ci/MatlabBuilder/config.jelly
- src/main/resources/com/mathworks/ci/UseMatlabVersionBuildWrapper/config.jelly
We have Jenkins issue opened with some security vulnerabilities  as per the suggestions this PR contains the fix. 
* ReproductionStep
Add a dangerous XML called VersionInfo.xml into the Jenkins controller file system using an "Execute Shell” build step.
Payload:
echo '
<!DOCTYPE foo [ <!ENTITY xxe SYSTEM "file://<CustomPath>"> ]>
<MathWorks_version_info>
<release>
&xxe;
</release>
</MathWorks_version_info>' > VersionInfo.xml
Add an “Archive the artifacts” post build step
**/*.xml
Build the Job
Go into the "configure job"
Check “Use MATLAB version" under the "Build Environment" section.
Fill the "MATLAB root" with ./work/jobs/<JobName>/builds/<BuildNumber>/archive/
OR
Navigate to:
<JenkinsInstanceURL>/descriptorByName/com.mathworks.ci.UseMatlabVersionBuildWrapper/checkMatlabRootFolder?matla …
> Addressed  Jenkins security issues

- src/main/resources/+ciplugins/+jenkins/BuildReportPlugin.m
- src/main/resources/com/mathworks/ci/BuildArtifactAction/summary.jelly
This is patch fix for issue reported by Braess Hennings as detailed below. 
<details><summary>Details</summary>
<p>
In various  projects the underlying jobs failed with the following error message:
** Finished buildApp
** Closed project 'SignalManagement'
{Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.
Error in ciplugins.jenkins.BuildReportPlugin/runTaskGraph (line 20)
fprintf(fID, '%s',s);
Error in matlab.buildtool.BuildRunner/evaluateMethodOnPlugins (line 256)
[varargout{1:nargout}] = plugin.(methodName)(pluginData);
Error in matlab.buildtool.BuildRunner/run (line 222)
runner.evaluateMethodOnPlugins("runTaskGraph", runner.PluginData.runTaskGraph);
Error in buildtool (line 39)
result = runner.run(plan, taskName, taskArgs, runArgs{:});
Error in …
> Patch fix for file error issue

- src/main/java/com/mathworks/ci/BuildArtifactAction.java
- src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java
- src/test/java/integ/com/mathworks/ci/BuildArtifactActionTest.java
This PR closes #320 
The PR includes the fix for the warning messages displayed under Jenkins server logs once runMATLABBuild` is executed. 
* Issue was `FilePath` object was getting serialised as mentioned in warning logs below 
* Remove Unwanted `FailePath` object from `BuildArtifactAction` file.
```
May 27, 2024 1:14:42 PM WARNING hudson.FilePath _getChannelForSerialization
A FilePath object is being serialized when it should not be, indicating a bug in a plugin. See https://www.jenkins.io/redirect/filepath-serialization for details.
[java.io](http://java.io/).NotSerializableException: The calling thread Thread[Handling GET /job/free/ from 172.19.148.116 : Jetty (winstone)-20 Job/index.jelly AbstractProject/sidepanel.jelly HistoryWidget/index.jelly,5,main] has no associated channel. …
```
> Fixed issue #320

- pom.xml
- src/main/java/com/mathworks/ci/utilities/MatlabCommandRunner.java
- src/test/java/unit/com/mathworks/ci/utilities/MatlabCommandRunnerTest.java
Updated the plugin to contain the ARM version of run-matlab-command to support maca64. Fixes issue [328](https://github.com/mathworks/jenkins-matlab-plugin/issues/328)
> Update run-matlab-command version, add maca support

- src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java
- src/main/java/com/mathworks/ci/actions/RunMatlabCommandAction.java
- src/main/java/com/mathworks/ci/actions/RunMatlabTestsAction.java
- src/main/java/com/mathworks/ci/utilities/MatlabCommandRunner.java
- src/test/java/unit/com/mathworks/ci/actions/RunMatlabBuildActionTest.java
- src/test/java/unit/com/mathworks/ci/actions/RunMatlabCommandActionTest.java
- src/test/java/unit/com/mathworks/ci/actions/RunMatlabTestsActionTest.java
- src/test/java/unit/com/mathworks/ci/utilities/MatlabCommandRunnerTest.java
Not a fix for issue [332](https://github.com/mathworks/jenkins-matlab-plugin/issues/332). I still need to think through what the consequences for having the temporary scripts self destruct would be. E.g. would we be resilient to page faults at high load, does this severely hinder debuggability, etc...
However, this should slightly improve performance as now the `MatlabCommandRunner` objects can be cleaned up before JVM shutdown. Especially for very long running Jenkins servers / agents this should be an improvement.
> Improve teardown

- src/main/java/com/mathworks/ci/BuildArtifactAction.java
- src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java
- src/main/java/com/mathworks/ci/utilities/MatlabCommandRunner.java
- src/main/resources/+ciplugins/+jenkins/BuildReportPlugin.m
- src/test/java/integ/com/mathworks/ci/RunMatlabBuildBuilderTest.java
- src/test/java/integ/com/mathworks/ci/RunMatlabBuildStepTest.java
- src/test/java/integ/com/mathworks/ci/RunMatlabCommandBuilderTest.java
- src/test/java/integ/com/mathworks/ci/RunMatlabCommandStepTest.java
- src/test/java/integ/com/mathworks/ci/RunMatlabTestsBuilderTest.java
- src/test/java/integ/com/mathworks/ci/RunMatlabTestsStepTest.java
- src/test/java/unit/com/mathworks/ci/actions/RunMatlabBuildActionTest.java
- src/test/java/unit/com/mathworks/ci/utilities/MatlabCommandRunnerTest.java
This should address the issue with the code coverage, without needing to delete the generated scripts + binary until the end of the step when they are no longer needed.
If a the workspace is `//some/path/workspace`, now the files will be copied into `//some/path/workspace@tmp/matlab-uuid`. Currently they are copied into `//some/path/workspace/.matlab/tempDir-uuid`.
Removed the integration tests checking for a `.matlab` folder because checking that the temp directory is created properly and in the right place is already covered by the unit tests and is implementation detail rathern than part of the interface that we need to remain invariant.
> Switch to using a temporary directory on the agent external to the WS.

- src/main/java/com/mathworks/ci/BuildArtifactAction.java
- src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java
- src/main/resources/+ciplugins/+jenkins/TaskRunProgressPlugin.m
- src/main/resources/com/mathworks/ci/BuildArtifactAction/index.jelly
- src/main/resources/com/mathworks/ci/BuildArtifactAction/summary.jelly
- src/test/java/integ/com/mathworks/ci/BuildArtifactActionTest.java
- src/test/java/unit/com/mathworks/ci/actions/RunMatlabBuildActionTest.java
This PR Closes #338 
* Added `actionID` to identify each build task separately.
* Under Jenkins root folder now files are getting store with `actionID` postfixed to it eg `buildArtifact<actionID>.jason` 
* `TaskRunProgressPlugin.m` now attaches `actionID` to the each task to avoid conflicting links.
***
***
***
***
**Note: There are a few open questions here about the summary page where we can see multiple summaries as shown below. Please let me know your thoughts on the same if we need to continue as shown below. combining the summary has some UI 
limitations from Jenkins side.**  
* **We are adding `actionID` in the logf sentinals to avoid conflicting hyperlinks in case both build runs the same tasks. Should we support this ? per me its very rare that under same job somebody would run …
> Fixed issue 338

- src/main/java/com/mathworks/ci/freestyle/RunMatlabCommandBuilder.java
- src/main/resources/com/mathworks/ci/freestyle/RunMatlabCommandBuilder/config.jelly
- src/main/resources/config.properties
- src/test/java/integ/com/mathworks/ci/RunMatlabCommandBuilderTest.java
Fixed geck # 2221893 
* `Command` text box under `Run MATLAB Command` now checks if the the command box is empty 
* Empty command box shows an error message 
* Added Integ tests
> Added check for command textbox

- CONFIGDOC.md
Hi, Kapil. I decided not to explicitly mention the Run MATLAB Command/`runMATLABCommand` step for this feature. The existing text sounds comprehensive enough.
Once we finalize this pull request, I will need to get a quick editorial review for the added sentence.
> documenting changes to the table of task results

- src/main/java/com/mathworks/ci/tools/MatlabInstaller.java
The release validation had an annotation that was causing some sort of http request. It ended up causing a weird bug during form validation.
> Remove unused imports and fix validation bug

- pom.xml
- src/main/java/com/mathworks/ci/MatlabInstallation.java
- src/main/java/com/mathworks/ci/UseMatlabVersionBuildWrapper.java
- src/main/java/com/mathworks/ci/Utilities.java
- src/main/java/com/mathworks/ci/tools/MatlabInstaller.java
This change puts `matlab-batch` in `$MATLAB_ROOT/bin` directory and adding that to path. The reason for this is because in our current `MatlabInstallation` code there is no info about the node or node channel being run. If we use FilePath as I before, there is a problem where it will use Windows style paths on Linux nodes if the server is hosted on Windows.
It is also a bit strange that we add `$MATLAB_ROOT/..` (installation home) to path even for MATLAB installations that were not configured by Install Automatically. This could add unintended folders to path for self-managed MATLAB installations.
> Fix matlab batch path bug

- src/main/resources/com/mathworks/ci/tools/MatlabInstaller/help-release.html
Addressing comments for https://github.com/mathworks/jenkins-matlab-plugin/issues/394
It was decided that the Release help text was not the correct place to discuss this limitation, but it will handled in the doc.
> Fix help text for release

- pom.xml
- src/main/java/com/mathworks/ci/tools/MatlabInstaller.java
- src/main/java/com/mathworks/ci/tools/MatlabRelease.java
Resolve latest release and use that to determine name of MATLAB folder. Also revert change where I bumped version in `pom.xml` because Vahila said that's part of the release process.
https://github.com/mathworks/jenkins-matlab-plugin/issues/392
> Resolve latest release issue

- src/main/java/com/mathworks/ci/tools/MatlabInstaller.java
chmod after copying matlab-batch instead of before. The copy of `matlab-batch` inside of `MATLAB_ROOT/bin` did not have correct permissions after copying so licensing was failing.
> Fix matlab-batch permissions

- src/main/java/com/mathworks/ci/tools/MatlabInstaller.java
Change Automatic Installation name to use capital R in version name (ex: R2024b instead of r2024b).
> Update release format for install automatically
