- Jenkinsfile
Added Jenkinsfile to build all subsequent builds automatically on jenkins infrastructure.
> Added Jenkinfile under root

- pom.xml
Updating the pom file after release complete.
> update pom after release

- src/main/java/com/mathworks/ci/MatlabBuilder.java
Added fix to support Jenkins environment variables during build.
> Fix to supoprt Jenkins environment variables.

- src/main/java/com/mathworks/ci/MatlabBuilder.java
- src/test/java/com/mathworks/ci/MatlabBuilderTest.java
custom commands are run using eval() function 
escaping all double quotes to get appropriate command
> Custom command is run after escaping imbalanced double quotes

- README.md
- azure-pipelines.yml
- src/main/java/com/mathworks/ci/MatlabBuilder.java
Updated the README doc to explain configuration for matrix support.
> Update README for Matrix build support.

- pom.xml
This will keep MathWorks repo in sync post new release.
> Post release POM merge

- src/main/java/com/mathworks/ci/MatlabBuilder.java
- src/test/java/com/mathworks/ci/MatlabBuilderTest.java
Scratch file generation will happen only for Automatic mode.
> Scratch file copy operation restricted to Automatic mode only.

- src/main/java/com/mathworks/ci/MatlabBuilder.java
- src/main/java/com/mathworks/ci/MatlabReleaseInfo.java
- src/main/resources/config.properties
- src/test/java/com/mathworks/ci/MatlabBuilderTest.java
- src/test/resources/testconfig.properties
Added changes to support remote nodes on Jenkins plugin. with these changes now user can run MATLAB on Jenkins agents.
> Added changes to support running MATLAB on remote agents.

- src/main/resources/com/mathworks/ci/MatlabBuilder/help-localMatlab.html
- src/main/resources/com/mathworks/ci/MatlabBuilder/help-matlabRoot.html
Also added help note if job is running on remote agents.
> Chnaged help file name as per action class.

- README.md
Removed unwanted platform-specific azure badges.
> Removed unwanted azure badges.

- CONFIGDOC.md
> replace MacOS with Mac

- src/main/java/com/mathworks/ci/MatlabBuilderConstants.java
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
* Used @databound constructors for each artifact class.
* Reduced scope of constant valuables to Artifact specific class.
* Single quote logic is scoped to Inputargs() method of builder class.
> Initial Changes to use data bound constructor.

- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
supporting backward compatibility for newly  added artifacts.
> Supporting backward compatibillity

- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-coberturaArtifact.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-junitArtifact.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-modelCoverageArtifact.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-pdfReportArtifact.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-stmResultsArtifact.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-tapArtifact.html
Updated help text for all test artifact checkboxes.
fix for #96 
PDF :
JUnit 
TAP : 
Stm : 
Cobertura code : 
Cobertura Model Coverage  :
> Updated help text for artifact checkboxes

- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/test/java/com/mathworks/ci/RunMatlabCommandBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
Reverts mathworks/jenkins-matlab-plugin#122 
To avoid this getting included in the upcoming release.
> Revert "Fix Java Temp Path discrepancy for Window"

- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/test/java/com/mathworks/ci/RunMatlabCommandBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
- src/test/java/com/mathworks/ci/TestStepExecution.java
This fix has been pre-approved in PR https://github.com/mathworks/jenkins-matlab-plugin/pull/122 
Raising new PR to merge to dev branch 'dev_main'
> Temp path issue

- azure-pipelines.yml
Change code coverage tool to JaCoCo
> Change code coverage tool to JaCoCo

- azure-pipelines.yml
- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/test/java/com/mathworks/ci/RunMatlabCommandBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
This PR is to merge qualified changes to master branch.
Changes in this qualification branch : 
- Fix temp path generation to remove multiple delimiters.
- Change code coverage collection tool to JaCoCo
> 2.1.3 snapshot qualification temp path

- azure-pipelines.yml
- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/test/java/com/mathworks/ci/RunMatlabCommandBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
synching Hot fix changes to dev_main
> Hot fixes issue 132

- src/main/java/com/mathworks/ci/MatlabBuild.java
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/main/java/com/mathworks/ci/RunMatlabTestsStep.java
- src/main/java/com/mathworks/ci/SourceFolder.java
- src/main/java/com/mathworks/ci/SourceFolderPaths.java
- src/main/java/com/mathworks/ci/Utilities.java
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-sourceFolder.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsStep/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabTestsStep/help-sourceFolder.html
- src/main/resources/com/mathworks/ci/SourceFolder/config.jelly
- src/test/java/com/mathworks/ci/RunMatlabTestBuilderPersistenceTest.java
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
This PR contains changes for :
- Adding Source Folder option to Pipeline Project.
- Adding Source Folder option to FreeStyle Project.
- Adding unit test for Source Folder option.
- Adding unit test to validate RunMatlabTestBuilder Artifacts persistence after Restarting Jenkins.
This PR closes #63
> Add Source Folder option

- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
Bring back Bug Fixes from 2.1.4 Qual branch to dev_main
> Handle apostrophe in file path value

- pom.xml
> Next release update 

- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/main/java/com/mathworks/ci/SelectByFolder.java
- src/main/java/com/mathworks/ci/SourceFolder.java
- src/main/java/com/mathworks/ci/SourceFolderPaths.java
- src/main/java/com/mathworks/ci/TestFolders.java
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/SelectByTag/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/config.jelly
- src/main/resources/com/mathworks/ci/SelectByFolder/config.jelly
- src/main/resources/com/mathworks/ci/SelectByTag/config.jelly
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
*Added Support to Filter tets using Folder and Tag name in freestyle.
> Test filter freestyle

- src/main/resources/com/mathworks/ci/MatlabInstallationAxis/config.jelly
- src/main/resources/com/mathworks/ci/MatlabInstallationAxis/help.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-sourceFolder.html
- src/main/resources/com/mathworks/ci/UseMatlabVersionBuildWrapper/help-matlabRootFolder.html
- src/main/resources/com/mathworks/ci/UseMatlabVersionBuildWrapper/help.html
- This PR closes #177 
- Addresses certain comments from https://github.com/mathworks/jenkins-matlab-plugin/pull/173#discussion_r550309652
> Add doc for MATLAB Axis

- CONFIGDOC.md
- examples/Run-MATLAB-Tests.md
- src/main/resources/com/mathworks/ci/MatlabInstallationAxis/config.jelly
- src/main/resources/com/mathworks/ci/MatlabInstallationAxis/help.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-selectByFolder.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-selectByTag.html
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/help-sourceFolder.html
- src/main/resources/com/mathworks/ci/UseMatlabVersionBuildWrapper/help-matlabRootFolder.html
- src/main/resources/com/mathworks/ci/UseMatlabVersionBuildWrapper/help.html
- src/test/java/com/mathworks/ci/RunMatlabTestsBuilderTest.java
This PR merges changes from the 3.0.0-Qualification branch (release as 2.4.0) to dev_main
> Get changes from 3.0.0 qualification

- CONFIGDOC.md
- README.md
- examples/Run-MATLAB-Tests.md
- Documented support for stage failures in Pipeline projects.
- Added a note about the licensing issue on Windows platforms.
- Made enhancements to the landing page, the configuration guide, and the example. 
@nbhoski and @abhargav-mw: 
It will be great if you can review the entire changes.
> document support for stage failures

- src/main/java/com/mathworks/ci/MatlabReleaseInfo.java
Pulling changes from QE branch to dev_main
> Add spotbugs false positive warning suppresion

- CONFIGDOC.md
- examples/Run-MATLAB-Tests.md
- src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
- src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/config.jelly
> 2.8.1 snapshot qualification

- .gitignore
- CONFIGDOC.md
- README.md
- examples/Run-MATLAB-Tests.md
- pom.xml
- src/main/java/com/mathworks/ci/MatlabBuildStepExecution.java
- src/main/java/com/mathworks/ci/RunMatlabBuildBuilder.java
- src/main/java/com/mathworks/ci/RunMatlabBuildStep.java
- src/main/resources/com/mathworks/ci/RunMatlabBuildBuilder/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabBuildBuilder/help-tasks.html
- src/main/resources/com/mathworks/ci/RunMatlabBuildStep/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabBuildStep/help-tasks.html
- src/main/resources/config.properties
- src/test/java/com/mathworks/ci/RunMatlabBuildBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabBuildBuilderTester.java
- src/test/java/com/mathworks/ci/RunMatlabBuildStepTest.java
- src/test/java/com/mathworks/ci/RunMatlabBuildStepTester.java
- src/test/resources/testconfig.properties
Support for Buildtool as a build task 
* Run MATLAB Build is new build step 
* User can provide build tasks to run 
* this step will invoke buildtool <provided_buildtask>
* eg `buildtool clean test`
* Multiple asks can be provided using spaces
> 2.9.1 snapshot qualification

- src/main/java/com/mathworks/ci/MatlabBuild.java
Windows is tricky! I changed the `ProcLauncher` in MatlabBuild.java to take in an ordered set of arguments so that we can split `startupOpts` on spaces. This resolves the issue with CMD treating strings differently from bash. Let me know if you have any flags on the changes
> Rewrite how startup options are parsed, so that they can be split

- src/main/java/com/mathworks/ci/MatlabBuildStepExecution.java
- src/main/java/com/mathworks/ci/RunMatlabBuildBuilder.java
- src/main/resources/com/mathworks/ci/BuildArtifactAction/index.jelly
* Added Build visulization support for Jenkins Pipeline 
* Fixed runmatlabbuildbuilder issue after merge conflict
> Build visulization support for pipeline

- src/main/resources/+ciplugins/+jenkins/BuildReportPlugin.m
> Bugfix 281

- pom.xml
Update the maven release on Qualification branchh which will synch the version on both mathworks org and Jenkins org
> Update the maven release 

- pom.xml
- src/main/java/com/mathworks/ci/BuildTargetNote.java
- src/main/resources/+ciplugins/+jenkins/BuildReportPlugin.m
- src/main/resources/com/mathworks/ci/BuildArtifactAction/index.jelly
- src/main/resources/com/mathworks/ci/BuildArtifactAction/summary.jelly
Merging the bug fixed on qualification
> 2.11.2 snapshot qualification

- .gitignore
- src/main/java/com/mathworks/ci/BuildOptions.java
- src/main/java/com/mathworks/ci/MatlabBuildStepExecution.java
- src/main/java/com/mathworks/ci/RunMatlabBuildBuilder.java
- src/main/java/com/mathworks/ci/RunMatlabBuildStep.java
- src/main/resources/com/mathworks/ci/BuildOptions/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabBuildBuilder/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabBuildBuilder/help-buildOptions.html
- src/main/resources/com/mathworks/ci/RunMatlabBuildBuilder/help-startupOptions.html
- src/main/resources/com/mathworks/ci/RunMatlabBuildStep/config.jelly
- src/main/resources/com/mathworks/ci/RunMatlabBuildStep/help-buildOptions.html
- src/main/resources/com/mathworks/ci/RunMatlabBuildStep/help-startupOptions.html
- src/test/java/com/mathworks/ci/RunMatlabBuildBuilderTest.java
- src/test/java/com/mathworks/ci/RunMatlabBuildStepTest.java
- Add build options for both **freestyle** and **pipeline** projects types.
> Add build options

- src/main/resources/com/mathworks/ci/BuildArtifactAction/summary.jelly
> Fixed issue 298

- pom.xml
> Prepare for next release 

- src/main/java/com/mathworks/ci/tools/MatlabInstaller.java
- src/test/java/unit/com/mathworks/ci/tools/MatlabInstallerUnitTest.java
Updated @databoundseeter from Version to Release
> Changed Version to release in setter

- src/main/java/com/mathworks/ci/tools/MatlabInstaller.java
Updating qual branch with changes from https://github.com/mathworks/jenkins-matlab-plugin/pull/375
> remove unused imports and fix validation bug (#375)

- pom.xml
- src/main/java/com/mathworks/ci/BuildTargetNote.java
- src/main/java/com/mathworks/ci/MatlabInstallation.java
- src/main/java/com/mathworks/ci/MatlabReleaseInfo.java
- src/main/java/com/mathworks/ci/MatlabVersionNotFoundException.java
- src/main/java/com/mathworks/ci/UseMatlabVersionBuildWrapper.java
- src/main/java/com/mathworks/ci/Utilities.java
- src/main/java/com/mathworks/ci/tools/MatlabInstaller.java
- src/main/java/com/mathworks/ci/utilities/MatlabCommandRunner.java
- src/main/resources/com/mathworks/ci/MatlabInstallation/help-home.html
- src/test/java/integ/com/mathworks/ci/RunMatlabTestsStepTest.java
This changes fixes the following issues:
https://github.com/mathworks/jenkins-matlab-plugin/issues/384
https://github.com/mathworks/jenkins-matlab-plugin/issues/380
https://github.com/mathworks/jenkins-matlab-plugin/issues/379
> Fix open issues for next release

- CONFIGDOC.md
- Revamped the Tool section of the plugin configuration guide
- Added content about tool configuration and licensing
> DOC: Configure tools using MATLAB Package Manager

- CONFIGDOC.md
- examples/Run-MATLAB-Tests.md
- pom.xml
- src/main/java/com/mathworks/ci/MatlabInstallation.java
- src/main/java/com/mathworks/ci/UseMatlabVersionBuildWrapper.java
- src/main/java/com/mathworks/ci/Utilities.java
- src/main/java/com/mathworks/ci/tools/MatlabInstaller.java
- src/main/java/com/mathworks/ci/tools/MatlabRelease.java
- src/main/resources/com/mathworks/ci/tools/MatlabInstaller/help-release.html
Merge 2.16.0 snapshot qualification to dev_main
> Merge 2.16.0 snapshot qualification to dev_main

- Jenkinsfile
> Update to Java 11

- pom.xml
Sync jenkinsci/master to mathworks/dev_main
> Preparing for next release
